# Install more recent versions of some CLI utilities
brew 'coreutils'
brew 'git'
brew 'grep'
brew 'gzip'
brew 'less'
brew 'lsof'
brew 'make'
brew 'vim'
brew 'whois'
brew 'zsh'

# Install command line utilities
brew 'diff-so-fancy'
brew 'elixir'
brew 'exa'
brew 'fd'
brew 'fzf'
brew 'gh'
brew 'git-extras'
brew 'hyperfine'
brew 'node'
brew 'pigz'
brew 'procs'
brew 'ripgrep'
brew 'sd'
brew 'tealdeer'
brew 'tokei'
brew 'wget'
brew 'zopfli'

# Install native apps
tap 'homebrew/cask-fonts'
tap 'homebrew/cask-versions'
cask '1password'
cask 'alfred'
cask 'appcleaner'
cask 'discord'
cask 'firefox-developer-edition'
cask 'flux'
cask 'font-sf-mono-for-powerline'
cask 'google-chrome-beta'
cask 'gpg-suite-no-mail'
cask 'iterm2'
cask 'rectangle'
cask 'spotify'
cask 'sublime-merge'
cask 'sublime-text'
cask 'vlc'
