set -add global autoinfo normal

colorscheme gruvbox-light

map global insert <c-a> <home>
map global insert <c-b> <left>
map global insert <c-e> <end>
map global insert <c-f> <right>

map global normal <c-p> ': fzf-mode<ret>'

source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/fzf.kak"
set-option global fzf_file_command 'rg'

plug "andreyorst/powerline.kak" %{
  hook -once global WinCreate .* %{
    powerline-separator none
  }
}

plug "ul/kak-lsp" do %{
  cargo build --release --locked
  cargo install --force
}

